arch:
  - amd64
  - ppc64le
  
language: go

go:
  - 1.13
  - 1.14
  - 1.15

    
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - $HOME/gopath/bin/goveralls -repotoken AMPGDzgJC5gzUpwfXcBApSg37OLodAUlJ
